[package]
name = "gold_price_prediction"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.19"
zip = "8.6.0"
plotters = {version = "0.3.3", optional=true}
plotters-cairo = {version = "0.9.0", optional= true}
gtk4 = {version = "0.11.3", optional=true}
ureq = "3.3.0"
serde = { version = "1.0.228", features = ["derive"] }
csv = "1.4.0"
ndarray = {version = "0.16.1", features = ["serde"]}
linfa = { version = "0.8.1" }
linfa-linear = {version= "0.8.1", features=["serde"]}
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
serde_json = "1.0.150"
actix-web = "4.13.0"
chrono = "0.4.44"
actix-cors = "0.7.1"

[features]
default = []
visualization = ["dep:plotters", "dep:plotters-cairo", "dep:gtk4"]

[profile.release]
strip = true
lto = true
opt-level="z"

