name: Continuos Delivery
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    name: Build & Publish Binaries
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'ubuntu-22.04-arm'
            args: ''
          - platform: 'windows-2022'
            args: ''
          - platform: 'windows-11-arm'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Build & Upload to Release
        uses: Keshav-writes-code/publish-rust-binaries@main
        with:
          args: ${{ matrix.args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
